TW-64306: Output prior release
im-open/git-version-lite pull request #38
Opened 2023-04-08 23:07 UTC by bradyclifford

https://jira.extendhealth.com/browse/TW-64306

# Summary of PR changes
Output prior version.

When pushing PR comments with the next version, in some cases it is helpful to update said comments with current release when a major or minor bump is not generated.  My team is using this in various scenarios and would rather not have to compute the previous version ourselves.  Since this action already gets the previous version, it seemed easy enough to include it as an output.

## PR Requirements
- [x] For major, minor, or breaking changes, at least one of the commit messages contains the appropriate `+semver:` keywords.
  - See the *Incrementing the Version* section of the repository's README.md for more details.
- [x] The action code does not contain sensitive information.

*NOTE: If the repo's workflow could not automatically update the `README.md`, it should be updated manually with the next version.  For javascript actions, if the repo's workflow could not automatically recompile the action it should also be updated manually as part of the PR.*

2023-04-10 12:59 UTC, JosephDSchwartz requested changes

2023-04-10 12:59 UTC, JosephDSchwartz commented on src/main.js
> +      NEXT_MAJOR_VERSION: nextVersion.minor,
```suggestion
      NEXT_MAJOR_VERSION: nextVersion.major,
```

2023-04-10 16:32 UTC, mike-schenk reviewed
Looks pretty good.

I wonder why remove the `outputs:` from action.yml though instead of adding all the outputs that this action _does_ set?

2023-04-13 03:29 UTC, bradyclifford commented
> Looks pretty good.
> 
> I wonder why remove the `outputs:` from action.yml though instead of adding all the outputs that this action _does_ set?

Add the outputs there doesn't not add any value in my opinion.  Or in other words, it doesn't change the functionality of the action.  Since the outputs and inputs are already defined in the readme.

But if you want me to add them, I will add them.

2023-04-13 16:35 UTC, mike-schenk commented
> > Looks pretty good.
> > I wonder why remove the `outputs:` from action.yml though instead of adding all the outputs that this action _does_ set?
> 
> Adding the outputs there doesn't not add any value in my opinion. Or in other words, it doesn't change the functionality of the action. Since the outputs and inputs are already defined in the readme.
> 
> But if you want me to add them, I will add them.

I think add them.

I wish GitHub would just not even have the `outputs` property if they're not going to do anything with it, but since it's actually there and documented, it _seems_ like it would be a good idea to keep it up-to-date. It would be nice if the action's documentation could be generated from the properties in the .yml file so we didn't have the duplication.

2023-04-26 18:09 UTC, mike-schenk approved these changes

2023-04-26 18:13 UTC, merged