SRE-208 - Adding additional outputs when setting prerelease input.
im-open/git-version-lite pull request #49
Opened 2024-10-14 22:32 UTC by jsclifford

# Summary of PR changes

* Adding the following outputs.  

| `PRIOR_VERSION_NO_PREFIX`              | The previous `major.minor.patch` version without the tag prefix                   |
| `NEXT_VERSION_NOLABEL`                 | The next `major.minor.patch` version without pre-release label                    |
| `NEXT_VERSION_NOLABEL_NO_PREFIX`       | The next `major.minor.patch` version without the tag prefix and pre-release label |
| `NEXT_MINOR_NOLABEL_VERSION`           | The next `major.minor` version without pre-release label                          |
| `NEXT_MINOR_VERSION_NOLABEL_NO_PREFIX` | The next `major.minor` version without the tag prefix and pre-release label       |
| `NEXT_MAJOR_NOLABEL_VERSION`           | The next `major` version without pre-release label                                |
| `NEXT_MAJOR_VERSION_NOLABEL_NO_PREFIX` | The next `major` version without the tag prefix and pre-release label             |

## PR Requirements
- [ ] For major, minor, or breaking changes, at least one of the commit messages contains the appropriate `+semver:` keywords.
  - See the *Incrementing the Version* section of the repository's README.md for more details.
- [ ] The action code does not contain sensitive information.

*NOTE: If the repo's workflow could not automatically update the `README.md`, it should be updated manually with the next version.  For javascript actions, if the repo's workflow could not automatically recompile the action it should also be updated manually as part of the PR.*

2024-10-15 02:45 UTC, mike-schenk requested changes
`NEXT_MINOR_VERSION_NOLABEL` and `NEXT_MAJOR_VERSION_NOLABEL` (and their `*NO_PREFIX` counterparts) are always equivalent to `NEXT_MINOR_VERSION` and `NEXT_MAJOR_VERSION` respectively. So those new outputs are unnecessary.

That just leaves `NEXT_VERSION_NOLABEL`. To match the previous output name format, it would be `NEXT_VERSION_NO_LABEL` and `NEXT_VERSION_NO_LABEL_NO_PREFIX`

However, the name `NEXT_RELEASE_VERSION` is probably even better because it indicates more what it _is_ than what it's _not_.

2024-10-15 15:32 UTC, jsclifford commented
I am in the process of renaming to NEXT_RELEASE_VERSION.  Thanks for helping me coin a more descriptive label

2024-10-15 20:13 UTC, jsclifford commented
@mike-schenk  I have updated to address your required changes.  Please review.

2024-10-17 16:23 UTC, mike-schenk approved these changes

2024-10-17 16:29 UTC, mike-schenk approved these changes

2024-10-17 16:41 UTC, cesar2532 approved these changes

2024-10-17 16:41 UTC, merged